FROM node:18

WORKDIR /home/node/app

COPY package*.json ./

ARG API_URL
ARG BUCKET_ACCESS_KEY_ID
ARG BUCKET_SECRET_ACCESS_KEY
ARG BUCKET_REGION
ARG BUCKET_NAME

ENV API_URL ${API_URL}
ENV BUCKET_ACCESS_KEY_ID ${BUCKET_ACCESS_KEY_ID}
ENV BUCKET_SECRET_ACCESS_KEY ${BUCKET_SECRET_ACCESS_KEY}
ENV BUCKET_REGION ${BUCKET_REGION}
ENV BUCKET_NAME ${BUCKET_NAME}

RUN npm install

COPY . .

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

EXPOSE 3000

CMD [ "npm", "start" ]

