name: Run performance testing

on:
  pull_request:
    branches:
      - main 

jobs: 
  performanceTesting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.zip
        unzip apache-jmeter-5.4.1.zip
        export JMETER_HOME=$GITHUB_WORKSPACE/apache-jmeter-5.4.1
        export PATH=$JMETER_HOME/bin:$PATH
    - name: Install JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.zip
        unzip apache-jmeter-5.4.1.zip
        export JMETER_HOME=$GITHUB_WORKSPACE/apache-jmeter-5.4.1
        export PATH=$JMETER_HOME/bin:$PATH
    - name: Run JMeter test
      run: |
        jmeter -n -t JDD-Performance-Testing.jmx -l results.jtl -e -o report
    - name: Upload JMeter report
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: report
